In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
odd_array = np.arange(1,20,2) # Vector of odd numbers
odd_array                     # Show vector
bool_array = odd_array > 11   # Boolean conditional array
bool_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
useful_Array = odd_array[bool_array] # The values we want
useful_Array

array([13, 15, 17, 19])

In [6]:
# This code is more compact
compact = odd_array[odd_array > 11] # One line
compact

array([13, 15, 17, 19])

In [ ]:
# Exercise

In [7]:
# 5x10 Array of even numbers between 0 and 100.
large_array = np.arange(0,100,2).reshape(5,10)
large_array # show

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [8]:
greater_than_80 = large_array[large_array > 80]
greater_than_80

array([82, 84, 86, 88, 90, 92, 94, 96, 98])

In [10]:
reshaped_80 = np.reshape(greater_than_80,(3,3))
reshaped_80

array([[82, 84, 86],
       [88, 90, 92],
       [94, 96, 98]])