In [2]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

freq = np.arange(10); values = np.random.randn(10)
freq; values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 3.02545836,  0.01110861, -0.48904884, -0.31339478,  0.66277462,
       -0.17370335,  0.61987673, -1.78104506, -0.6123151 ,  0.01950197])

In [4]:
np.reshape(freq,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
np.reshape(values,(2,5))

array([[ 3.02545836,  0.01110861, -0.48904884, -0.31339478,  0.66277462],
       [-0.17370335,  0.61987673, -1.78104506, -0.6123151 ,  0.01950197]])

In [15]:
A = values.max();B = values.min();
C = values.argmax()+1; D = values.argmin()+1

print('Maximum value: {}\nMinimum value: {}\
n\nItem {} is the maximum value, while item {}\n\
is the minimum value'.format(A,B,C,D))

Maximum value: 3.0254583601171365
Minimum value: -1.781045064480701n
Item 1 is the maximum value, while item 8
is the minimum value


In [ ]:
# indexing and selecting arrays

In [21]:
# Indexing a vector array (values)
print('Full array: ')
values
print('First item:')
values[0] # grabbing 1st item
print('Last item:')
values[-1] # grabbing last item
print('2nd and 3rd items:')
values[1:3] # grabbing 2nd & 3rd item
print('4th and other items up to 8th item:')
values[3:8] # item 4 to 8

Full array: 


array([ 3.02545836,  0.01110861, -0.48904884, -0.31339478,  0.66277462,
       -0.17370335,  0.61987673, -1.78104506, -0.6123151 ,  0.01950197])

First item:


3.0254583601171365

Last item:


0.019501973203569594

2nd and 3rd items:


array([ 0.01110861, -0.48904884])

4th and other items up to 8th item:


array([-0.31339478,  0.66277462, -0.17370335,  0.61987673, -1.78104506])

In [24]:
num_list = list(range(11)) # list from 0-10
num_list
list_slice = num_list[:4]  # first 4 items
list_slice                 # display slice
list_slice[:] = [5,7,9,3]  # Re-assigning elements
list_slice                 # display updated values

# checking for the changes

print('The original list changes!') if list_slice == num_list[:4]\
else print('no changes in original list')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[0, 1, 2, 3]

[5, 7, 9, 3]

no changes in original list


In [25]:
# Checking the broadcast feature of arrays

num_array = np.arange(11)    # array from 0-10
num_array                    # display array
array_slice = num_array[:4]  # first 4 items
array_slice                  # display slice
array_slice[:] = [5,7,9,3]   # re-assigning elements
array_slice
num_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([0, 1, 2, 3])

array([5, 7, 9, 3])

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Here is an array allocation without broadcast
num_array                                  # Array from the last example
array_slice = num_array.copy()[:4]         # copies the first 4 items of the array copy
array_slice                                # display array
array_slice[:] = 10                        # re-assign array
array_slice                                # display updated values
num_array                                  # checking original array

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

array([5, 7, 9, 3])

array([10, 10, 10, 10])

array([ 5,  7,  9,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# grabbing elements from a matrix

In [30]:
# Creating the matrix
matrix = np.array(([5,10,15],[20,25,30],[35,40,45]))
matrix                                 # display matrix
matrix[1]                              # grabbing second row
matrix[2][0]                           # grabbing 35
matrix[0:2]                            # grabbing first 2 rows
matrix[2,2]                            # grabbing 45

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

array([20, 25, 30])

35

array([[ 5, 10, 15],
       [20, 25, 30]])

45

In [31]:
# Grabbing the second column
column_slice = matrix[:,1:2] # Assigning to variable
column_slice

array([[10],
       [25],
       [40]])

In [32]:
# 5x10 Array of even numbers between 0 and 100.
large_array = np.arange(0,100,2).reshape(5,10)
large_array # show

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [33]:
num96 = large_array[4,8]
num96

96

In [34]:
slice_44_54 = large_array[2:3,2:8]
slice_44_54

array([[44, 46, 48, 50, 52, 54]])

In [36]:
slice_26_44 = large_array[1:5,2:4]
slice_26_44

array([[24, 26],
       [44, 46],
       [64, 66],
       [84, 86]])