In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [7]:
# Array - Array operations
# Declaring two arrays of 10 elements

Array1 = np.arange(10).reshape(2,5)
Array2 = np.random.randn(10).reshape(2,5)
Array1; Array2                              # Show the arrays

# Addition
Array_sum = Array1 + Array2
print('Addition:')
Array_sum                                   # Show result array

# Subtraction
Array_minus = Array1 - Array2
print('Subtraction:')
Array_minus                                 # Show

# Multiplication

Array_product = Array1 * Array2
print('Multiplication:')
Array_product                               # Show

# Division

Array_divide = Array1 / Array2
print('Divisio')
Array_divide                                # Show

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[-0.1638077 ,  0.6965274 ,  0.33986262, -1.61551626,  0.01472644],
       [ 0.27431344, -0.17944164, -1.53719655, -0.15355153,  1.535912  ]])

Addition:


array([[-0.1638077 ,  1.6965274 ,  2.33986262,  1.38448374,  4.01472644],
       [ 5.27431344,  5.82055836,  5.46280345,  7.84644847, 10.535912  ]])

Subtraction:


array([[0.1638077 , 0.3034726 , 1.66013738, 4.61551626, 3.98527356],
       [4.72568656, 6.17944164, 8.53719655, 8.15355153, 7.464088  ]])

Multiplication:


array([[ -0.        ,   0.6965274 ,   0.67972523,  -4.84654877,
          0.05890576],
       [  1.37156718,  -1.07664985, -10.76037587,  -1.22841224,
         13.82320803]])

Division:


array([[ -0.        ,   1.43569371,   5.8847308 ,  -1.85699152,
        271.62031518],
       [ 18.2273244 , -33.43705486,  -4.55374427, -52.09977379,
          5.8597107 ]])

In [ ]:
# Array - Scalar operations

In [19]:
# Scalar - Array operations
new_array = np.arange(0,11) # Array of values from 0-10
print('New_array:')
new_array                   # Show
Sc = 100                    # Scalar value

# let us make an array with a range from 100 - 110 (using + )
add_array = new_array + Sc   # Adding 100 to every item
print('\nAdd_array')
add_array                    # Show

# Let us make an array of 100s (using -)
centurion = add_array - new_array
print('\nCenturion')
centurion                     # Show

# Let us do some multiplication (using *)
multiplex = new_array * 100
multiplex                     # Show

# division [take care], let us deliberately generate an error. We will do a divide by Zero

err_vec = new_array / new_array
print('\nError_vec')
err_vec                        # Show

New_array:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


Add_array


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])


Centurion


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])


Error_vec


/tmp/ipykernel_4363/4138118655.py:23: RuntimeWarning: invalid value encountered in true_divide
  err_vec = new_array / new_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])