In [3]:
# This is a list of integers
Int_list = [1,2,3,4,5]
Int_list

[1, 2, 3, 4, 5]

In [15]:
# import syntax
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import numpy as np

np.array(Int_list)


array([1, 2, 3, 4, 5])

In [16]:
x = np.array(Int_list)
type(x)

numpy.ndarray

In [18]:
x.ndim # this shows how many dimensions the array has.

1

In [19]:
x.shape # This shows the shape.

(5,)

In [20]:
# This is a matrix
x = [1,2,3]
y = [4,5,6]

my_list = [y,x] # nested list

my_matrix = np.array(my_list) # creating the matrix

A = my_matrix.ndim
B = my_matrix.shape

# Printing
print('Resulting matrix:\n\n',my_matrix,'\n\nDimensions:',A,'\nshape (rows,columns):',B)

Resulting matrix:

 [[4 5 6]
 [1 2 3]] 

Dimensions: 2 
shape (rows,columns): (2, 3)


In [21]:
# this finds the transpose of the matrix
t_matrix = my_matrix.transpose()
t_matrix

array([[4, 1],
       [5, 2],
       [6, 3]])

In [23]:
C = t_matrix.ndim
D = t_matrix.shape
C
D

2

(3, 2)

In [24]:
# Array of even numbers between 0 and 10.
Even_array = np.arange(0,11,2)
Even_array

array([ 0,  2,  4,  6,  8, 10])

In [25]:
Even_array2 = np.arange(0,11,2,dtype='float')
Even_array2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
# Arrays of linearly spaced points
A = np.linspace(0,5,5) # 5 equal points
B = np.linspace(51,100) # 50 equal points between 51 & 100
print('Here are the arrays:\n')
A
B

Here are the arrays:



array([0.  , 1.25, 2.5 , 3.75, 5.  ])

array([ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,
        62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
        73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
        84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,
        95.,  96.,  97.,  98.,  99., 100.])

In [27]:
np.zeros(3) # A vector of 3 elements.
np.zeros((2,3)) # A matrix of 6 elements i.e 2 rows, 3 columns

array([0., 0., 0.])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones(3) # A vector of 3 elements.
np.ones((2,3)) # A matrix of 6 elements i.e. 2 rows, 3 columns.

array([1., 1., 1.])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.eye(2) # A matrix of 4 elements 2 rows, 2 columns.
np.eye(3) # A matrix of 6 elements 3 rows, 3 columns.

array([[1., 0.],
       [0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.rand(2) # A vector of 2 random value.
np.random.rand(2,3) # A matrix of 6 random values.

array([0.69464248, 0.6771047 ])

array([[0.73652438, 0.00992015, 0.91240207],
       [0.0341566 , 0.99147336, 0.96406622]])

In [14]:
np.random.randn(2)
np.random.randn(2,3)

array([[ 1.21066095, -0.35618412, -0.48687078],
       [-0.18097228,  0.89276796,  0.18547389]])

In [35]:
np.random.randint(1,5) # A random value between 1 and 5.
np.random.randint(1,100,6) # A vector of 6 random values.
np.random.randint(1,100,(2,3)) # A matrix of 6 random values.

2

array([51, 38, 61, 40, 56,  7])

array([[92, 31, 92],
       [79, 41, 62]])

In [36]:
# creating a dice roll game with randint()
# Defining the function

def roll_dice():
    """This function displays a dice roll value when called"""
    
    dice1 = np.random.randint(1,7) # This allows 6 to be inclusive.
    dice2 = np.random.randint(1,7)
    
    # Display condition
    if dice1 == dice2:
        print('Roll:', dice1,'&',dice2,'\ndoubles!')
        if dice1 == 1:
            print('snake eyes!\n')
    else:
        print('Roll:',dice1,'&',dice2)

In [55]:
roll_dice()

Roll: 1 & 1 
doubles!
snake eyes!

