In [3]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [6]:
# Scalar - Array operations
new_array = np.arange(0,11) # Array of values from 0-10
print('New_array:')
new_array                   # Show
Sc = 100                    # Scalar value
# let us make an array with a range from 100 - 110 (using + )
add_array = new_array + Sc   # Adding 100 to every item
print('\nAdd_array')
add_array                    # Show

New_array:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


Add_array


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
# Using U-Funcs
U_add = np.add(new_array,Sc) # addition
U_add                        # show

U_sub = np.subtract(add_array,new_array)
U_sub                        # show

U_log = np.log(new_array)    # Natural log
U_log                        # show

sinusoid = np.sin(new_array) # Sine wave
sinusoid                     # Show

# Alternatively, we can use the .method
new_array.max()              # find maximum
np.max(new_array)            # same thing

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

/tmp/ipykernel_4772/136475696.py:8: RuntimeWarning: divide by zero encountered in log
  U_log = np.log(new_array)    # Natural log


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

10

10

In [11]:
new_array
sinusoid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])